BASE_URL = "https://raw.githubusercontent.com/gentoosiasta/genshin_bot/refs/heads/main/builds/"
CVE_URL = "https://genshin.ch/"
IMAGENES = {
    "albedo": {"url":[BASE_URL + "Albedo.png"], "cve": CVE_URL + "es-build-038-t3"},
    "alhaitham": {"url":[BASE_URL + "Alhaitham.png"], "cve": CVE_URL + "es-build-078-t3"},
    "aloy": {"url":[
        BASE_URL + "Aloy_Freeze.png",
        BASE_URL + "Aloy_Melt.png",
        BASE_URL + "Aloy_Support.png"
        ], "cve": CVE_URL + "es-build-062-t3"},
    "amber": {"url":[
        BASE_URL + "Amber_Melt_Charged.png",
        BASE_URL + "Amber_Melt.png",],"cve": CVE_URL + "es-build-021-t3"},
    "arlecchino": {"url":[BASE_URL + "Arlecchino.png"], "cve": CVE_URL + "es-build-096-t3"},
    "ayaka": {"url":[BASE_URL + "Ayaka.png"], "cve": CVE_URL + "es-build-002-t3"},
    "ayato": {"url":[BASE_URL + "Ayato.png"], "cve": CVE_URL + "es-build-066-t3"},
    "baizhu": {"url":[BASE_URL + "Baizhu.png"], "cve": CVE_URL + "es-build-082-t3"},
    "barbara": {"url":[BASE_URL + "Barbara.png"], "cve": CVE_URL + "es-build-014-t3"},
    "beidou": {"url":[BASE_URL + "Beidou.png"], "cve": CVE_URL + "es-build-024-t3"},
    "bennett": {"url":[BASE_URL + "Bennett.png"], "cve": CVE_URL + "es-build-032-t3"},
    "candace": {"url":[
        BASE_URL + "Candace_Bloom.png",
        BASE_URL + "Candace_Support.png",
        BASE_URL + "Candace-DPS.png"], "cve": CVE_URL + "es-build-072-t3"},
    "charlotte": {"url":[BASE_URL + "Charlotte.png"], "cve": CVE_URL + "es-build-088-t3"},
    "chasca": {"url":[BASE_URL + "Chasca.png"], "cve": CVE_URL + "es-build-104-t3"},
    "chevreuse": {"url":[
        BASE_URL + "Chevreuse-DPS.png",
        BASE_URL + "Chevreuse-Support.png"], "cve": CVE_URL + "es-build-090-t3"},
    "chiori": {"url":[BASE_URL + "Chiori.png"], "cve": CVE_URL + "es-build-094-t3"},
    "chongyun": {"url":[BASE_URL + "Chongyun.png"], "cve": CVE_URL + "es-build-036-t3"},
    "citlali": {"url":[BASE_URL + "Citlali.png"], "cve": CVE_URL + "es-build-107-t3"},
    "clorinde": {"url":[BASE_URL + "Clorinde.png"], "cve": CVE_URL + "es-build-098-t3"},
    "collei": {"url":[BASE_URL + "Collei.png"], "cve": CVE_URL + "es-build-067-t3"},
    "cyno": {"url":[BASE_URL + "Cyno.png"], "cve": CVE_URL + "es-build-071-t3"},
    "dahlia": {"url":[BASE_URL + "Dahlia.png"], "cve": CVE_URL + "es-build-115-t3"},
    "dehya": {"url":[BASE_URL + "Dehya_DPS.png",
        BASE_URL + "Dehya_Support.png"], "cve": CVE_URL + "es-build-079-t3"},
    "diluc": {"url":[BASE_URL + "Diluc.png"], "cve": CVE_URL + "es-build-016-t3"},
    "diona": {"url":[BASE_URL + "Diona.png"], "cve": CVE_URL + "es-build-039-t3"},
    "dori": {"url":[BASE_URL + "Dori_DPS.png",
        BASE_URL + "Dori_Hyperbloom.png",
        BASE_URL + "Dori_Support.png"], "cve": CVE_URL + "es-build-068-t3"},
    "emilie": {"url":[BASE_URL + "Emilie.png"], "cve": CVE_URL + "es-build-099-t3"},
    "escoffier": {"url":[
        BASE_URL + "Escoffier_Freeze.png",
        BASE_URL + "Escoffier_Support.png"], "cve": CVE_URL + "es-build-112-t3"},
    "eula": {"url":[BASE_URL + "Eula.png"], "cve": CVE_URL + "es-build-051-t3"},
    "faruzan": {"url":[BASE_URL + "Faruzan.png"], "cve": CVE_URL + "es-build-076-t3"},
    "fischl": {"url":[BASE_URL + "Fischl.png"], "cve": CVE_URL + "es-build-031-t3"},
    "freminet": {"url":[BASE_URL + "Freminet_Cryo.png",
        BASE_URL + "Freminet_Fisical.png"], "cve": CVE_URL + "es-build-085-t3"},
    "furina": {"url":[BASE_URL + "Furina.png"], "cve": CVE_URL + "es-build-089-t3"},
    "gaming": {"url":[BASE_URL + "Gaming.png"], "cve": CVE_URL + "es-build-092-t3"},
    "ganyu": {"url":[BASE_URL + "Ganyu_Freeze.png",
        BASE_URL + "Ganyu_Melt.png"], "cve": CVE_URL + "es-build-037-t3"},
    "gorou": {"url":[BASE_URL + "Gorou.png"], "cve": CVE_URL + "es-build-055-t3"},
    "heizou": {"url":[BASE_URL + "Heizou_DPS.png",
        BASE_URL + "Heizou_Driver.png",
        BASE_URL + "Heizou_Support.png"], "cve": CVE_URL + "es-build-059-t3"},
    "hutao": {"url":[BASE_URL + "Hu Tao.png"], "cve": CVE_URL + "es-build-046-t3"},
    "iansan": {"url":[BASE_URL + "Iansan.png"], "cve": CVE_URL + "es-build-110-t3"},
    "ifa": {"url":[BASE_URL + "Ifa_Anemo_DPS.png",
        BASE_URL + "Ifa_Swirl_DPS.png"], "cve": CVE_URL + "es-build-113-t3"},
    "ineffa": {"url":[BASE_URL + "Ineffa.png"], "cve": CVE_URL + "es-build-116-t3"},
    "itto": {"url":[BASE_URL + "Itto.png"], "cve": CVE_URL + "es-build-057-t3"},
    "jean": {"url":[BASE_URL + "Jean_Healer.png",
        BASE_URL + "Jean_Sunfire.png"], "cve": CVE_URL + "es-build-003-t3"},
    "kashina": {"url":[BASE_URL + "Kashina.png"], "cve": CVE_URL + "es-build-100-t3"},
    "kaeya": {"url":[BASE_URL + "Kaeya_Freeze.png",
        BASE_URL + "Kaeya_Melt.png"], "cve": CVE_URL + "es-build-015-t3"},
    "kaveh": {"url":[BASE_URL + "Kaveh.png"], "cve": CVE_URL + "es-build-081-t3"},
    "kazuha": {"url":[BASE_URL + "Kazuha.png"], "cve": CVE_URL + "es-build-047-t3"},
    "keqing": {"url":[BASE_URL + "Keqing_Aggravate.png",
        BASE_URL + "Keqing_Electro.png"], "cve": CVE_URL + "es-build-042-t3"},
    "kinich": {"url":[BASE_URL + "Kinich.png"], "cve": CVE_URL + "es-build-101-t3"},
    "kirara": {"url":[BASE_URL + "Kirara.png"], "cve": CVE_URL + "es-build-061-t3"},
    "klee": {"url":[BASE_URL + "Klee.png"], "cve": CVE_URL + "es-build-029-t3"},
    "kokomi": {"url":[BASE_URL + "Kokomi_Bloom.png",
        BASE_URL + "Kokomi_Driver.png",
        BASE_URL + "Kokomi_Support.png"], "cve": CVE_URL + "es-build-054-t3"},
    "kuki": {"url":[BASE_URL + "Shinobu_Hyperbloom.png",
        BASE_URL + "Shinobu_Quicken.png"], "cve": CVE_URL + "es-build-065-t3"},
    "lanyan": {"url":[BASE_URL + "Lanyan.png"], "cve": CVE_URL + "es-build-108-t3"},
    "layla": {"url":[BASE_URL + "Layla_DPS.png",
        BASE_URL + "Layla_Shielder.png"], "cve": CVE_URL + "es-build-074-t3"},
    "lisa": {"url":[BASE_URL + "Lisa.png"], "cve": CVE_URL + "es-build-006-t3"},
    "lynette": {"url":[BASE_URL + "Lynette_DPS.png",
        BASE_URL + "Lynette_Reaction.png",
        BASE_URL + "Lynette_Support.png"], "cve": CVE_URL + "es-build-083-t3"},
    "lyney": {"url":[BASE_URL + "Lyney.png"], "cve": CVE_URL + "es-build-084-t3"},
    "mavuika": {"url":[BASE_URL + "Mavuika_DPS.png",
        BASE_URL + "Mavuika_Support.png"], "cve": CVE_URL + "es-build-106-t3"},
    "mika": {"url":[BASE_URL + "Mika.png"], "cve": CVE_URL + "es-build-080-t3"},
    "mizuki": {"url":[BASE_URL + "Mizuki.png"], "cve": CVE_URL + "es-build-109-t3"},
    "mona": {"url":[BASE_URL + "Mona.png"], "cve": CVE_URL + "es-build-041-t3"},
    "mualani": {"url":[BASE_URL + "Mualani.png"], "cve": CVE_URL + "es-build-102-t3"},
    "nahida": {"url":[BASE_URL + "Nahida.png"], "cve": CVE_URL + "es-build-073-t3"},
    "navia": {"url":[BASE_URL + "Navia.png"], "cve": CVE_URL + "es-build-091-t3"},
    "neuvillette": {"url":[BASE_URL + "Neuvillette.png"], "cve": CVE_URL + "es-build-087-t3"},
    "nilou": {"url":[BASE_URL + "Nilou.png"], "cve": CVE_URL + "es-build-070-t3"},
    "ningguang": {"url":[BASE_URL + "Ningguang.png"], "cve": CVE_URL + "es-build-027-t3"},
    "noelle": {"url":[BASE_URL + "Noelle.png"], "cve": CVE_URL + "es-build-034-t3"},
    "ororon": {"url":[BASE_URL + "Oro.png"], "cve": CVE_URL + "es-build-105-t3"},
    "qiqi": {"url":[BASE_URL + "Qiqi.png"], "cve": CVE_URL + "es-build-035-t3"},
    "raiden": {"url":[BASE_URL + "Raiden_Shogun_Aggravate.png",
        BASE_URL + "Raiden_Shogun_DPS.png",
        BASE_URL + "Raiden_Shogun_Hyper-bloom.png"], "cve": CVE_URL + "es-build-042-t3"},
    "razor": {"url":[BASE_URL + "Razor_Aggravate.png",
        BASE_URL + "Razor_Physical.png",
        BASE_URL + "Razor_Transformative.png"], "cve": CVE_URL + "es-build-020-t3"},
    "rosaria": {"url":[BASE_URL + "Rosaria_Freeze.png",
        BASE_URL + "Rosaria_Melt.png"], "cve": CVE_URL + "es-build-045-t3"},
    "sara": {"url":[BASE_URL + "Kujou_Sara.png"], "cve": CVE_URL + "es-build-056-t3"},
    "sayu": {"url":[BASE_URL + "Sayu_DPS.png",
        BASE_URL + "Sayu_Support.png"], "cve": CVE_URL + "es-build-053-t3"},
    "sethos": {"url":[BASE_URL + "Sethos.png"], "cve": CVE_URL + "es-build-097-t3"},
    "shenhe": {"url":[BASE_URL + "Shenhe.jpg"], "cve": CVE_URL + "es-build-063-t3"},
    "sigewinne": {"url":[BASE_URL + "Sigewinne.png"], "cve": CVE_URL + "es-build-095-t3"},
    "skirk": {"url":[BASE_URL + "Skirk.png"], "cve": CVE_URL + "es-build-114-t3"},
    "sucrose": {"url":[BASE_URL + "Sucrose.png"], "cve": CVE_URL + "es-build-043-t3"},
    "tartaglia": {"url":[BASE_URL + "Tartaglia.png"], "cve": CVE_URL + "es-build-033-t3"},
    "thoma": {"url":[BASE_URL + "Thoma_Burgeon.png",
        BASE_URL + "Thoma_Support.png"], "cve": CVE_URL + "es-build-050-t3"},
    "tighnari": {"url":[BASE_URL + "Tighnari.png"], "cve": CVE_URL + "es-build-069-t3"},
    "traveler": {"url":[BASE_URL + "Traveler_Dendro_1.png",
        BASE_URL + "Traveler_Dendro_2.png",
        BASE_URL + "Traveler_Hydro.png",
        BASE_URL + "Traveler_Pyro_DPS.png",
        BASE_URL + "Traveler_Pyro_Support.png",], "cve": ""},
    "varesa": {"url":[BASE_URL + "Varuna.png"], "cve": CVE_URL + "es-build-111-t3"},
    "venti": {"url":[BASE_URL + "Venti.png"], "cve": CVE_URL + "es-build-022-t3"},
    "wanderer": {"url":[BASE_URL + "Wanderer.png"], "cve": CVE_URL + "es-build-075-t3"},
    "wriothesley": {"url":[BASE_URL + "Wriothesley_Freeze.png",
        BASE_URL + "Wriothesley_Melt.png"], "cve": CVE_URL + "es-build-086-t3"},
    "xiangling": {"url":[BASE_URL + "Xiangling_DPS.png",
        BASE_URL + "Xiangling_Support.png"], "cve": CVE_URL + "es-build-023-t3"},
    "xianyun": {"url":[BASE_URL + "Xianyun.png"], "cve": CVE_URL + "es-build-093-t3"},
    "xiao": {"url":[BASE_URL + "Xiao.png"], "cve": CVE_URL + "es-build-026-t3"},
    "xilonen": {"url":[BASE_URL + "Xilonen.png"], "cve": CVE_URL + "es-build-103-t3"},
    "xingqiu": {"url":[BASE_URL + "Xingqiu.png"], "cve": CVE_URL + "es-build-025-t3"},
    "xinyan": {"url":[BASE_URL + "Xinyan_Physical_DPS.png",
        BASE_URL + "Xinyan_Pyro_DPS.png",
        BASE_URL + "Xinyan_Shielder.png"], "cve": CVE_URL + "es-build-044-t3"},
    "yae": {"url":[BASE_URL + "Yae_Miko.png"], "cve": CVE_URL + "es-build-058-t3"},
    "yaemiko": {"url":[BASE_URL + "Yane_Miko.png"], "cve": CVE_URL + "es-build-058-t3"},
    "yanfei": {"url":[BASE_URL + "Yanfei.png"], "cve": CVE_URL + "es-build-048-t3"},
    "yaoyao": {"url":[BASE_URL + "Yaoyao.png"], "cve": CVE_URL + "es-build-077-t3"},
    "yelan": {"url":[BASE_URL + "Yelan.png"], "cve": CVE_URL + "es-build-060-t3"},
    "yoimiya": {"url":[BASE_URL + "Yoimiya.png"], "cve": CVE_URL + "es-build-049-t3"},
    "yunjin": {"url":[BASE_URL + "Yun_Jin.png"], "cve": CVE_URL + "es-build-064-t3"},
    "zhongli": {"url":[BASE_URL + "Zhongli.png"], "cve": CVE_URL + "es-build-030-t3"},
}
